/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.usermanagement.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserInfo service. Represents a row in the &quot;CRM_UserInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.usermanagement.model.impl.UserInfoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.usermanagement.model.impl.UserInfoImpl}.
 * </p>
 *
 * @author phantoan
 * @see UserInfo
 * @see com.liferay.usermanagement.model.impl.UserInfoImpl
 * @see com.liferay.usermanagement.model.impl.UserInfoModelImpl
 * @generated
 */
@ProviderType
public interface UserInfoModel extends BaseModel<UserInfo>, ShardedModel,
	StagedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user info model instance should use the {@link UserInfo} interface instead.
	 */

	/**
	 * Returns the primary key of this user info.
	 *
	 * @return the primary key of this user info
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this user info.
	 *
	 * @param primaryKey the primary key of this user info
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the uuid of this user info.
	 *
	 * @return the uuid of this user info
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this user info.
	 *
	 * @param uuid the uuid of this user info
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the user code of this user info.
	 *
	 * @return the user code of this user info
	 */
	@AutoEscape
	public String getUserCode();

	/**
	 * Sets the user code of this user info.
	 *
	 * @param userCode the user code of this user info
	 */
	public void setUserCode(String userCode);

	/**
	 * Returns the user ID of this user info.
	 *
	 * @return the user ID of this user info
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user info.
	 *
	 * @param userId the user ID of this user info
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user info.
	 *
	 * @return the user uuid of this user info
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user info.
	 *
	 * @param userUuid the user uuid of this user info
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the username of this user info.
	 *
	 * @return the username of this user info
	 */
	@AutoEscape
	public String getUsername();

	/**
	 * Sets the username of this user info.
	 *
	 * @param username the username of this user info
	 */
	public void setUsername(String username);

	/**
	 * Returns the male of this user info.
	 *
	 * @return the male of this user info
	 */
	public boolean getMale();

	/**
	 * Returns <code>true</code> if this user info is male.
	 *
	 * @return <code>true</code> if this user info is male; <code>false</code> otherwise
	 */
	public boolean isMale();

	/**
	 * Sets whether this user info is male.
	 *
	 * @param male the male of this user info
	 */
	public void setMale(boolean male);

	/**
	 * Returns the birthday of this user info.
	 *
	 * @return the birthday of this user info
	 */
	public Date getBirthday();

	/**
	 * Sets the birthday of this user info.
	 *
	 * @param birthday the birthday of this user info
	 */
	public void setBirthday(Date birthday);

	/**
	 * Returns the address of this user info.
	 *
	 * @return the address of this user info
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this user info.
	 *
	 * @param address the address of this user info
	 */
	public void setAddress(String address);

	/**
	 * Returns the email of this user info.
	 *
	 * @return the email of this user info
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this user info.
	 *
	 * @param email the email of this user info
	 */
	public void setEmail(String email);

	/**
	 * Returns the phone of this user info.
	 *
	 * @return the phone of this user info
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this user info.
	 *
	 * @param phone the phone of this user info
	 */
	public void setPhone(String phone);

	/**
	 * Returns the department code of this user info.
	 *
	 * @return the department code of this user info
	 */
	@AutoEscape
	public String getDepartmentCode();

	/**
	 * Sets the department code of this user info.
	 *
	 * @param departmentCode the department code of this user info
	 */
	public void setDepartmentCode(String departmentCode);

	/**
	 * Returns the role of this user info.
	 *
	 * @return the role of this user info
	 */
	@AutoEscape
	public String getRole();

	/**
	 * Sets the role of this user info.
	 *
	 * @param role the role of this user info
	 */
	public void setRole(String role);

	/**
	 * Returns the group ID of this user info.
	 *
	 * @return the group ID of this user info
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this user info.
	 *
	 * @param groupId the group ID of this user info
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this user info.
	 *
	 * @return the company ID of this user info
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this user info.
	 *
	 * @param companyId the company ID of this user info
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this user info.
	 *
	 * @return the create date of this user info
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this user info.
	 *
	 * @param createDate the create date of this user info
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user info.
	 *
	 * @return the modified date of this user info
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user info.
	 *
	 * @param modifiedDate the modified date of this user info
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(UserInfo userInfo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<UserInfo> toCacheModel();

	@Override
	public UserInfo toEscapedModel();

	@Override
	public UserInfo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}